-- Tabela de clientes
CREATE TABLE IF NOT EXISTS clientes
(
    id_cliente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(255) NOT NULL,
    email varchar(255),
    endereco varchar(255),
    cnpj char(14),
    cpf char(11),
    inscricao_estadual varchar(50),
    tipo_pessoa varchar(20) DEFAULT 'J',
    numero integer,
    complemento varchar(100),
    cep varchar(10),
    uf varchar(2),
    cidade varchar(100),
    contatos varchar(200),
    telefone varchar(20),
    celular varchar(20),
    website varchar(100),
    CONSTRAINT clientes_tipo_pessoa_check CHECK (tipo_pessoa = ANY (ARRAY['F', 'J']))
);

-- Tabela de contratos_itens
CREATE TABLE IF NOT EXISTS contratos_itens
(
    id_contrato bigint GENERATED BY DEFAULT AS IDENTITY,
    id_cliente bigint NOT NULL,
    codigo_avlock varchar(255) NOT NULL,
    sistema varchar(255) NOT NULL,
    dias_liberacao integer,
    tipo_liberacao varchar(10) DEFAULT 'Recorrente',
    status_liberacao varchar(10) DEFAULT 'Inativo',
    observacoes varchar(255),
    appid integer,
    modalidade integer DEFAULT 253,
    CONSTRAINT contratos_itens_pkey PRIMARY KEY (id_cliente, codigo_avlock, sistema),
    CONSTRAINT contratos_id_cliente_fkey FOREIGN KEY (id_cliente)
        REFERENCES clientes (id_cliente),
    CONSTRAINT check_appid_when_chave_avlock CHECK (
        CASE
            WHEN chave_avlock IS NOT NULL AND chave_avlock <> '' THEN appid IS NOT NULL
            ELSE true
        END
    ),
    CONSTRAINT contratos_itens_dias_liberacao_check CHECK (dias_liberacao >= 1 AND dias_liberacao <= 365),
    CONSTRAINT contratos_itens_status_liberacao_check CHECK (status_liberacao = ANY (ARRAY['Ativo', 'Inativo'])),
    CONSTRAINT contratos_itens_tipo_liberacao_check CHECK (tipo_liberacao = ANY (ARRAY['Recorrente', 'Permanente']))
);

-- Comentários das colunas (opcional no Supabase, mas mantido para documentação)
COMMENT ON COLUMN contratos_itens.appid IS 'Serve para definir a versão do sistema Ex: 9000 = Versao 9.0';
COMMENT ON COLUMN contratos_itens.modalidade IS 'identifica o tipo de licença. Ex: STD, GOLD, PREMIUM - 253, 254, 255';


-- Tabela de contratos_itens
CREATE TABLE IF NOT EXISTS contratos_chaves
(
    id_chave bigint GENERATED BY DEFAULT AS IDENTITY,
    id_contrato bigint NOT NULL,
    ano_base integer,
    mes_base integer,
    chave_avlock varchar(128),  
    data_inicial TIMESTAMP WITH TIME ZONE, 
    data_final TIMESTAMP WITH TIME ZONE, 
    CONSTRAINT contratos_chaves_pkey PRIMARY KEY (id_contrato, ano_base, mes_base, chave_avlock),
    CONSTRAINT contratos_chaves_id_contrato_fkey FOREIGN KEY (id_contrato)
        REFERENCES contratos_itens (id_contrato),
    CONSTRAINT contratos_chaves_mes_base_check CHECK (mes_base >= 1 AND mes_base <= 12)
);